; generated by PrusaSlicer 2.7.3+win64 on 2024-04-04 at 12:24:39 UTC

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm


; printing object Shape-Box id:1 copy 0
; stop printing object Shape-Box id:1 copy 0

;TYPE:Custom
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

M140 S55 ; set bed temp
M104 S200 ; set extruder temp
M109 S200 ; wait for extruder temp
M190 S55 ; wait for bed temp

G28 ; Home all axes
M104 S215 ; set extruder temp 
BED_MESH_CALIBRATE AREA_START=82.1802,82.1802 AREA_END=148.82,148.82

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
M109 S215 ; wait for extruder temp
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position

G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-1.6 F2400
G1 Z.2 F6000
G1 X83.844 Y82.842
G1 Z.2
G1 E1.6 F2400
M204 S500
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X85.5 Y82.369 E.05292
G1 X145.5 Y82.369 E1.84363
G1 X147.02 Y82.762 E.04824
G1 X148.158 Y83.844 E.04825
G1 X148.631 Y85.5 E.05292
G1 X148.631 Y145.5 E1.84363
G1 X148.238 Y147.02 E.04824
G1 X147.156 Y148.158 E.04825
G1 X145.5 Y148.631 E.05292
G1 X85.5 Y148.631 E1.84363
G1 X83.98 Y148.238 E.04824
G1 X82.842 Y147.156 E.04825
G1 X82.369 Y145.5 E.05292
G1 X82.369 Y85.5 E1.84363
G1 X82.762 Y83.98 E.04824
G1 X83.803 Y82.886 E.0464
G1 X83.803 Y82.886 F6000
G1 X84.085 Y83.183
G1 F1200
G1 X84.205 Y83.069 E.00509
G1 X85.5 Y82.746 E.04101
G1 X145.5 Y82.746 E1.84363
G1 X146.917 Y83.139 E.04518
G1 X147.931 Y84.205 E.04521
G1 X148.254 Y85.5 E.04101
G1 X148.254 Y145.5 E1.84363
G1 X147.861 Y146.917 E.04518
G1 X146.795 Y147.931 E.04521
G1 X145.5 Y148.254 E.04101
G1 X85.5 Y148.254 E1.84363
G1 X84.083 Y147.861 E.04518
G1 X83.069 Y146.795 E.04521
G1 X82.746 Y145.5 E.04101
G1 X82.746 Y85.5 E1.84363
G1 X83.139 Y84.083 E.04518
G1 X84.042 Y83.224 E.0383
G1 X84.042 Y83.224 F6000
G1 X84.301 Y83.534
G1 F1200
G1 X84.56 Y83.317 E.01038
G1 X85.5 Y83.123 E.02949
G1 X145.5 Y83.123 E1.84363
G1 X146.807 Y83.515 E.04193
G1 X147.683 Y84.56 E.0419
G1 X147.877 Y85.5 E.02949
G1 X147.877 Y145.5 E1.84363
G1 X147.485 Y146.807 E.04193
G1 X146.44 Y147.683 E.0419
G1 X145.5 Y147.877 E.02949
G1 X85.5 Y147.877 E1.84363
G1 X84.193 Y147.485 E.04193
G1 X83.317 Y146.44 E.0419
G1 X83.123 Y145.5 E.02949
G1 X83.123 Y85.5 E1.84363
G1 X83.515 Y84.193 E.04193
G1 X84.255 Y83.572 E.02968
G1 E-1.12 F2400
;WIPE_START
G1 F4800
G1 X84.301 Y83.534 E-.02834
G1 X84.56 Y83.317 E-.1605
G1 X85.16 Y83.193 E-.29116
;WIPE_END
; printing object Shape-Box id:1 copy 0
G1 X86.187 Y86.187 F6000
G1 E1.6 F2400
;TYPE:Perimeter
G1 F1200
G1 X144.813 Y86.187 E1.80141
G1 X144.813 Y144.813 E1.80141
G1 X86.187 Y144.813 E1.80141
G1 X86.187 Y86.247 E1.79957
G1 X85.81 Y85.81 F6000
;TYPE:External perimeter
G1 F1200
G1 X145.19 Y85.81 E1.82458
G1 X145.19 Y145.19 E1.82458
G1 X85.81 Y145.19 E1.82458
G1 X85.81 Y85.87 E1.82274
G1 E-1.12 F2400
;WIPE_START
G1 F4800
G1 X85.81 Y85.81 E-.0285
G1 X86.761 Y85.81 E-.4515
;WIPE_END
G1 X144.692 Y87.07 F6000
G1 E1.6 F2400
;TYPE:Solid infill
;WIDTH:0.420187
G1 F1200
G1 X144.099 Y86.477 E.02578
G1 X143.566 Y86.477 E.01639
G1 X144.523 Y87.434 E.04161
G1 X144.523 Y87.968 E.01642
G1 X143.032 Y86.477 E.06482
G1 X142.499 Y86.477 E.01639
G1 X144.523 Y88.501 E.088
G1 X144.523 Y89.035 E.01642
G1 X141.965 Y86.477 E.11121
G1 X141.432 Y86.477 E.01639
G1 X144.523 Y89.568 E.13439
G1 X144.523 Y90.102 E.01642
G1 X140.898 Y86.477 E.1576
G1 X140.365 Y86.477 E.01639
G1 X144.523 Y90.635 E.18078
G1 X144.523 Y91.169 E.01642
G1 X139.831 Y86.477 E.20399
G1 X139.297 Y86.477 E.01642
G1 X144.523 Y91.703 E.22721
G1 X144.523 Y92.236 E.01639
G1 X138.764 Y86.477 E.25038
G1 X138.23 Y86.477 E.01642
G1 X144.523 Y92.77 E.2736
G1 X144.523 Y93.303 E.01639
G1 X137.697 Y86.477 E.29677
G1 X137.163 Y86.477 E.01642
G1 X144.523 Y93.837 E.31999
G1 X144.523 Y94.37 E.01639
G1 X136.63 Y86.477 E.34316
G1 X136.096 Y86.477 E.01642
G1 X144.523 Y94.904 E.36638
G1 X144.523 Y95.437 E.01639
G1 X135.563 Y86.477 E.38955
G1 X135.029 Y86.477 E.01642
G1 X144.523 Y95.971 E.41277
G1 X144.523 Y96.504 E.01639
G1 X134.496 Y86.477 E.43594
G1 X133.962 Y86.477 E.01642
G1 X144.523 Y97.038 E.45915
G1 X144.523 Y97.571 E.01639
G1 X133.429 Y86.477 E.48233
G1 X132.895 Y86.477 E.01642
G1 X144.523 Y98.105 E.50554
G1 X144.523 Y98.639 E.01642
G1 X132.361 Y86.477 E.52876
G1 X131.828 Y86.477 E.01639
G1 X144.523 Y99.172 E.55193
G1 X144.523 Y99.706 E.01642
G1 X131.294 Y86.477 E.57515
G1 X130.761 Y86.477 E.01639
G1 X144.523 Y100.239 E.59832
G1 X144.523 Y100.773 E.01642
G1 X130.227 Y86.477 E.62154
G1 X129.694 Y86.477 E.01639
G1 X144.523 Y101.306 E.64471
G1 X144.523 Y101.84 E.01642
G1 X129.16 Y86.477 E.66793
G1 X128.627 Y86.477 E.01639
G1 X144.523 Y102.373 E.6911
G1 X144.523 Y102.907 E.01642
G1 X128.093 Y86.477 E.71432
G1 X127.56 Y86.477 E.01639
G1 X144.523 Y103.44 E.73749
G1 X144.523 Y103.974 E.01642
G1 X127.026 Y86.477 E.76071
G1 X126.493 Y86.477 E.01639
G1 X144.523 Y104.507 E.78388
G1 X144.523 Y105.041 E.01642
G1 X125.959 Y86.477 E.8071
G1 X125.426 Y86.477 E.01639
G1 X144.523 Y105.574 E.83027
G1 X144.523 Y106.108 E.01642
G1 X124.892 Y86.477 E.85349
G1 X124.358 Y86.477 E.01642
G1 X144.523 Y106.642 E.8767
G1 X144.523 Y107.175 E.01639
G1 X123.825 Y86.477 E.89988
G1 X123.291 Y86.477 E.01642
G1 X144.523 Y107.709 E.92309
G1 X144.523 Y108.242 E.01639
G1 X122.758 Y86.477 E.94626
G1 X122.224 Y86.477 E.01642
G1 X144.523 Y108.776 E.96948
G1 X144.523 Y109.309 E.01639
G1 X121.691 Y86.477 E.99265
G1 X121.157 Y86.477 E.01642
G1 X144.523 Y109.843 E1.01587
G1 X144.523 Y110.376 E.01639
G1 X120.624 Y86.477 E1.03904
G1 X120.09 Y86.477 E.01642
G1 X144.523 Y110.91 E1.06226
G1 X144.523 Y111.443 E.01639
G1 X119.557 Y86.477 E1.08543
G1 X119.023 Y86.477 E.01642
G1 X144.523 Y111.977 E1.10865
G1 X144.523 Y112.51 E.01639
G1 X118.49 Y86.477 E1.13182
G1 X117.956 Y86.477 E.01642
G1 X144.523 Y113.044 E1.15504
G1 X144.523 Y113.578 E.01642
G1 X117.422 Y86.477 E1.17825
G1 X116.889 Y86.477 E.01639
G1 X144.523 Y114.111 E1.20143
G1 X144.523 Y114.645 E.01642
G1 X116.355 Y86.477 E1.22464
G1 X115.822 Y86.477 E.01639
G1 X144.523 Y115.178 E1.24782
G1 X144.523 Y115.712 E.01642
G1 X115.288 Y86.477 E1.27103
G1 X114.755 Y86.477 E.01639
G1 X144.523 Y116.245 E1.29421
G1 X144.523 Y116.779 E.01642
G1 X114.221 Y86.477 E1.31742
G1 X113.688 Y86.477 E.01639
G1 X144.523 Y117.312 E1.3406
G1 X144.523 Y117.846 E.01642
G1 X113.154 Y86.477 E1.36381
G1 X112.621 Y86.477 E.01639
G1 X144.523 Y118.379 E1.38699
G1 X144.523 Y118.913 E.01642
G1 X112.087 Y86.477 E1.4102
G1 X111.554 Y86.477 E.01639
G1 X144.523 Y119.446 E1.43337
G1 X144.523 Y119.98 E.01642
G1 X111.02 Y86.477 E1.45659
G1 X110.487 Y86.477 E.01639
G1 X144.523 Y120.514 E1.47979
G1 X144.523 Y121.047 E.01639
G1 X109.953 Y86.477 E1.50298
G1 X109.419 Y86.477 E.01642
G1 X144.523 Y121.581 E1.5262
G1 X144.523 Y122.114 E.01639
G1 X108.886 Y86.477 E1.54937
G1 X108.352 Y86.477 E.01642
G1 X144.523 Y122.648 E1.57259
G1 X144.523 Y123.181 E.01639
G1 X107.819 Y86.477 E1.59576
G1 X107.285 Y86.477 E.01642
G1 X144.523 Y123.715 E1.61898
G1 X144.523 Y124.248 E.01639
G1 X106.752 Y86.477 E1.64215
G1 X106.218 Y86.477 E.01642
G1 X144.523 Y124.782 E1.66536
G1 X144.523 Y125.315 E.01639
G1 X105.685 Y86.477 E1.68854
G1 X105.151 Y86.477 E.01642
G1 X144.523 Y125.849 E1.71175
G1 X144.523 Y126.382 E.01639
G1 X104.618 Y86.477 E1.73493
G1 X104.084 Y86.477 E.01642
G1 X144.523 Y126.916 E1.75814
G1 X144.523 Y127.449 E.01639
G1 X103.551 Y86.477 E1.78132
G1 X103.017 Y86.477 E.01642
G1 X144.523 Y127.983 E1.80453
G1 X144.523 Y128.517 E.01642
G1 X102.483 Y86.477 E1.82775
G1 X101.95 Y86.477 E.01639
G1 X144.523 Y129.05 E1.85092
G1 X144.523 Y129.584 E.01642
G1 X101.416 Y86.477 E1.87414
G1 X100.883 Y86.477 E.01639
G1 X144.523 Y130.117 E1.89731
G1 X144.523 Y130.651 E.01642
G1 X100.349 Y86.477 E1.92053
G1 X99.816 Y86.477 E.01639
G1 X144.523 Y131.184 E1.9437
G1 X144.523 Y131.718 E.01642
G1 X99.282 Y86.477 E1.96692
G1 X98.749 Y86.477 E.01639
G1 X144.523 Y132.251 E1.99009
G1 X144.523 Y132.785 E.01642
G1 X98.215 Y86.477 E2.01331
G1 X97.682 Y86.477 E.01639
G1 X144.523 Y133.318 E2.03648
G1 X144.523 Y133.852 E.01642
G1 X97.148 Y86.477 E2.0597
G1 X96.615 Y86.477 E.01639
G1 X144.523 Y134.385 E2.08287
G1 X144.523 Y134.919 E.01642
G1 X96.081 Y86.477 E2.10609
G1 X95.547 Y86.477 E.01642
G1 X144.523 Y135.453 E2.1293
G1 X144.523 Y135.986 E.01639
G1 X95.014 Y86.477 E2.15247
G1 X94.48 Y86.477 E.01642
G1 X144.523 Y136.52 E2.17569
G1 X144.523 Y137.053 E.01639
G1 X93.947 Y86.477 E2.19886
G1 X93.413 Y86.477 E.01642
G1 X144.523 Y137.587 E2.22208
G1 X144.523 Y138.12 E.01639
G1 X92.88 Y86.477 E2.24525
G1 X92.346 Y86.477 E.01642
G1 X144.523 Y138.654 E2.26847
G1 X144.523 Y139.187 E.01639
G1 X91.813 Y86.477 E2.29164
G1 X91.279 Y86.477 E.01642
G1 X144.523 Y139.721 E2.31486
G1 X144.523 Y140.254 E.01639
G1 X90.746 Y86.477 E2.33803
G1 X90.212 Y86.477 E.01642
G1 X144.523 Y140.788 E2.36125
G1 X144.523 Y141.321 E.01639
G1 X89.679 Y86.477 E2.38442
G1 X89.145 Y86.477 E.01642
G1 X144.523 Y141.855 E2.40764
G1 X144.523 Y142.388 E.01639
G1 X88.612 Y86.477 E2.43081
G1 X88.078 Y86.477 E.01642
G1 X144.523 Y142.922 E2.45403
G1 X144.523 Y143.456 E.01642
G1 X87.544 Y86.477 E2.47724
G1 X87.011 Y86.477 E.01639
G1 X144.523 Y143.989 E2.50042
G1 X144.523 Y144.523 E.01642
G1 X86.477 Y86.477 E2.52363
G1 X86.477 Y87.011 E.01642
G1 X143.989 Y144.523 E2.50042
G1 X143.455 Y144.523 E.01642
G1 X86.477 Y87.545 E2.4772
G1 X86.477 Y88.078 E.01639
G1 X142.922 Y144.523 E2.45403
G1 X142.388 Y144.523 E.01642
G1 X86.477 Y88.612 E2.43081
G1 X86.477 Y89.145 E.01639
G1 X141.855 Y144.523 E2.40764
G1 X141.321 Y144.523 E.01642
G1 X86.477 Y89.679 E2.38442
G1 X86.477 Y90.212 E.01639
G1 X140.788 Y144.523 E2.36125
G1 X140.254 Y144.523 E.01642
G1 X86.477 Y90.746 E2.33803
G1 X86.477 Y91.279 E.01639
G1 X139.721 Y144.523 E2.31486
G1 X139.187 Y144.523 E.01642
G1 X86.477 Y91.813 E2.29164
G1 X86.477 Y92.346 E.01639
G1 X138.654 Y144.523 E2.26847
G1 X138.12 Y144.523 E.01642
G1 X86.477 Y92.88 E2.24525
G1 X86.477 Y93.413 E.01639
G1 X137.587 Y144.523 E2.22208
G1 X137.053 Y144.523 E.01642
G1 X86.477 Y93.947 E2.19886
G1 X86.477 Y94.481 E.01642
G1 X136.519 Y144.523 E2.17565
G1 X135.986 Y144.523 E.01639
G1 X86.477 Y95.014 E2.15247
G1 X86.477 Y95.548 E.01642
G1 X135.452 Y144.523 E2.12926
G1 X134.919 Y144.523 E.01639
G1 X86.477 Y96.081 E2.10609
G1 X86.477 Y96.615 E.01642
G1 X134.385 Y144.523 E2.08287
G1 X133.852 Y144.523 E.01639
G1 X86.477 Y97.148 E2.0597
G1 X86.477 Y97.682 E.01642
G1 X133.318 Y144.523 E2.03648
G1 X132.785 Y144.523 E.01639
G1 X86.477 Y98.215 E2.01331
G1 X86.477 Y98.749 E.01642
G1 X132.251 Y144.523 E1.99009
G1 X131.718 Y144.523 E.01639
G1 X86.477 Y99.282 E1.96692
G1 X86.477 Y99.816 E.01642
G1 X131.184 Y144.523 E1.9437
G1 X130.651 Y144.523 E.01639
G1 X86.477 Y100.349 E1.92053
G1 X86.477 Y100.883 E.01642
G1 X130.117 Y144.523 E1.89731
G1 X129.584 Y144.523 E.01639
G1 X86.477 Y101.416 E1.87414
G1 X86.477 Y101.95 E.01642
G1 X129.05 Y144.523 E1.85092
G1 X128.516 Y144.523 E.01642
G1 X86.477 Y102.484 E1.82771
G1 X86.477 Y103.017 E.01639
G1 X127.983 Y144.523 E1.80453
G1 X127.449 Y144.523 E.01642
G1 X86.477 Y103.551 E1.78132
G1 X86.477 Y104.084 E.01639
G1 X126.916 Y144.523 E1.75814
G1 X126.382 Y144.523 E.01642
G1 X86.477 Y104.618 E1.73493
G1 X86.477 Y105.151 E.01639
G1 X125.849 Y144.523 E1.71175
G1 X125.315 Y144.523 E.01642
G1 X86.477 Y105.685 E1.68854
G1 X86.477 Y106.218 E.01639
G1 X124.782 Y144.523 E1.66536
G1 X124.248 Y144.523 E.01642
G1 X86.477 Y106.752 E1.64215
G1 X86.477 Y107.285 E.01639
G1 X123.715 Y144.523 E1.61898
G1 X123.181 Y144.523 E.01642
G1 X86.477 Y107.819 E1.59576
G1 X86.477 Y108.352 E.01639
G1 X122.648 Y144.523 E1.57259
G1 X122.114 Y144.523 E.01642
G1 X86.477 Y108.886 E1.54937
G1 X86.477 Y109.42 E.01642
G1 X121.58 Y144.523 E1.52615
G1 X121.047 Y144.523 E.01639
G1 X86.477 Y109.953 E1.50298
G1 X86.477 Y110.487 E.01642
G1 X120.513 Y144.523 E1.47976
G1 X119.98 Y144.523 E.01639
G1 X86.477 Y111.02 E1.45659
G1 X86.477 Y111.554 E.01642
G1 X119.446 Y144.523 E1.43337
G1 X118.913 Y144.523 E.01639
G1 X86.477 Y112.087 E1.4102
G1 X86.477 Y112.621 E.01642
G1 X118.379 Y144.523 E1.38699
G1 X117.846 Y144.523 E.01639
G1 X86.477 Y113.154 E1.36381
G1 X86.477 Y113.688 E.01642
G1 X117.312 Y144.523 E1.3406
G1 X116.779 Y144.523 E.01639
G1 X86.477 Y114.221 E1.31742
G1 X86.477 Y114.755 E.01642
G1 X116.245 Y144.523 E1.29421
G1 X115.712 Y144.523 E.01639
G1 X86.477 Y115.288 E1.27103
G1 X86.477 Y115.822 E.01642
G1 X115.178 Y144.523 E1.24782
G1 X114.644 Y144.523 E.01642
G1 X86.477 Y116.356 E1.2246
G1 X86.477 Y116.889 E.01639
G1 X114.111 Y144.523 E1.20143
G1 X113.577 Y144.523 E.01642
G1 X86.477 Y117.423 E1.17821
G1 X86.477 Y117.956 E.01639
G1 X113.044 Y144.523 E1.15504
G1 X112.51 Y144.523 E.01642
G1 X86.477 Y118.49 E1.13182
G1 X86.477 Y119.023 E.01639
G1 X111.977 Y144.523 E1.10865
G1 X111.443 Y144.523 E.01642
G1 X86.477 Y119.557 E1.08543
G1 X86.477 Y120.09 E.01639
G1 X110.91 Y144.523 E1.06226
G1 X110.376 Y144.523 E.01642
G1 X86.477 Y120.624 E1.03904
G1 X86.477 Y121.157 E.01639
G1 X109.843 Y144.523 E1.01587
G1 X109.309 Y144.523 E.01642
G1 X86.477 Y121.691 E.99265
G1 X86.477 Y122.224 E.01639
G1 X108.776 Y144.523 E.96948
G1 X108.242 Y144.523 E.01642
G1 X86.477 Y122.758 E.94626
G1 X86.477 Y123.291 E.01639
G1 X107.709 Y144.523 E.92309
G1 X107.175 Y144.523 E.01642
G1 X86.477 Y123.825 E.89988
G1 X86.477 Y124.359 E.01642
G1 X106.641 Y144.523 E.87666
G1 X106.108 Y144.523 E.01639
G1 X86.477 Y124.892 E.85349
G1 X86.477 Y125.426 E.01642
G1 X105.574 Y144.523 E.83027
G1 X105.041 Y144.523 E.01639
G1 X86.477 Y125.959 E.8071
G1 X86.477 Y126.493 E.01642
G1 X104.507 Y144.523 E.78388
G1 X103.974 Y144.523 E.01639
G1 X86.477 Y127.026 E.76071
G1 X86.477 Y127.56 E.01642
G1 X103.44 Y144.523 E.73749
G1 X102.907 Y144.523 E.01639
G1 X86.477 Y128.093 E.71432
G1 X86.477 Y128.627 E.01642
G1 X102.373 Y144.523 E.6911
G1 X101.84 Y144.523 E.01639
G1 X86.477 Y129.16 E.66793
G1 X86.477 Y129.694 E.01642
G1 X101.306 Y144.523 E.64471
G1 X100.773 Y144.523 E.01639
G1 X86.477 Y130.227 E.62154
G1 X86.477 Y130.761 E.01642
G1 X100.239 Y144.523 E.59832
G1 X99.705 Y144.523 E.01642
G1 X86.477 Y131.295 E.57511
G1 X86.477 Y131.828 E.01639
G1 X99.172 Y144.523 E.55193
G1 X98.638 Y144.523 E.01642
G1 X86.477 Y132.362 E.52872
G1 X86.477 Y132.895 E.01639
G1 X98.105 Y144.523 E.50554
G1 X97.571 Y144.523 E.01642
G1 X86.477 Y133.429 E.48233
G1 X86.477 Y133.962 E.01639
G1 X97.038 Y144.523 E.45915
G1 X96.504 Y144.523 E.01642
G1 X86.477 Y134.496 E.43594
G1 X86.477 Y135.029 E.01639
G1 X95.971 Y144.523 E.41277
G1 X95.437 Y144.523 E.01642
G1 X86.477 Y135.563 E.38955
G1 X86.477 Y136.096 E.01639
G1 X94.904 Y144.523 E.36638
G1 X94.37 Y144.523 E.01642
G1 X86.477 Y136.63 E.34316
G1 X86.477 Y137.163 E.01639
G1 X93.837 Y144.523 E.31999
G1 X93.303 Y144.523 E.01642
G1 X86.477 Y137.697 E.29677
G1 X86.477 Y138.23 E.01639
G1 X92.77 Y144.523 E.2736
G1 X92.236 Y144.523 E.01642
G1 X86.477 Y138.764 E.25038
G1 X86.477 Y139.298 E.01642
G1 X91.702 Y144.523 E.22716
G1 X91.169 Y144.523 E.01639
G1 X86.477 Y139.831 E.20399
G1 X86.477 Y140.365 E.01642
G1 X90.635 Y144.523 E.18078
G1 X90.102 Y144.523 E.01639
G1 X86.477 Y140.898 E.1576
G1 X86.477 Y141.432 E.01642
G1 X89.568 Y144.523 E.13439
G1 X89.035 Y144.523 E.01639
G1 X86.477 Y141.965 E.11121
G1 X86.477 Y142.499 E.01642
G1 X88.501 Y144.523 E.088
G1 X87.968 Y144.523 E.01639
G1 X86.477 Y143.032 E.06482
G1 X86.477 Y143.566 E.01642
G1 X87.434 Y144.523 E.04161
G1 X86.901 Y144.523 E.01639
G1 X86.308 Y143.93 E.02578
; stop printing object Shape-Box id:1 copy 0
G1 E-1.12 F2400
;WIPE_START
G1 F4800;_WIPE
G1 X86.901 Y144.523 E-.39835
G1 X87.073 Y144.523 E-.08165
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z2.2 F600 ; Move print head up
G1 X5 Y193.8 F6000 ; present print
G1 Z70.2 F600 ; Move print head further up
G1 Z150 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
; objects_info = {"objects":[{"name":"Shape-Box id:1 copy 0","polygon":[[145.500,145.500],[85.500,145.500],[85.500,85.500],[145.500,85.500]]}]}
; filament used [mm] = 346.31
; filament used [cm3] = 0.83
; filament used [g] = 1.03
; filament cost = 0.02
; total filament used [g] = 1.03
; total filament cost = 0.02
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 9m 14s
; estimated first layer printing time (normal mode) = 9m 14s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 3x3,228x3,228x228,3x228
; bed_temperature = 55
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 250
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/(ENDER|CR|SERMOON).*/ and nozzle_diameter[0]==0.4";"printer_notes!~/.*PRINTER_VENDOR_TRILAB.*/ and printer_notes!~/.*PRINTER_MODEL_MK4IS.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and num_extruders>1)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 500
; default_filament_profile = "Generic PLA @CREALITY"
; default_print_profile = "0.16 mm OPTIMAL (0.4 mm nozzle) @CREALITY"
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.85} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 55
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.98
; extrusion_width = 0.44
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 2
; filament_cooling_initial_speed = 3
; filament_cooling_moves = 1
; filament_cost = 21.5
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 14
; filament_loading_speed_start = 19
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 0
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "130 120 2.70968 2.93548 3.32258 3.83871 4.58065 5.54839 6.51613 7.35484 7.93548 8.16129| 0.05 2.66451 0.45 3.05805 0.95 4.05807 1.45 5.97742 1.95 7.69999 2.45 8.1936 2.95 11.342 3.45 11.4065 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Spectrum PLA @Template - po_kalibracji_2"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 20
; filament_unloading_speed_start = 100
; filament_vendor = Spectrum
; fill_angle = 45
; fill_density = 20%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 55
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 2
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 25
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.44
; infill_first = 0
; infill_overlap = 23%
; infill_speed = 48
; inherits_cummulative = "0.20 mm NORMAL (0.4 mm nozzle) @CREALITY";;"Creality Ender-3 (0.4 mm nozzle)"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 500
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.32
; max_print_height = 250
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.06
; min_print_speed = 10
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{print_time}_{digits(layer_height,1,2)}mm_{temperature[0]}C_{filament_type[0]}_{printer_model}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.44
; perimeter_generator = classic
; perimeter_speed = 36
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20 mm NORMAL (0.4 mm nozzle) @CREALITY - po_kalibracji_2
; printer_model = ENDER3
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_ENDER3\nPRINTER_HAS_BOWDEN
; printer_settings_id = Creality Ender-3 (0.4 mm nozzle) - po_kalibracji_2
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1.6
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0.2
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirts = 3
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.44
; solid_infill_speed = 45
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = ; Ender 3 Custom Start G-code\nG92 E0 ; Reset Extruder\n\nM140 S[first_layer_bed_temperature] ; set bed temp\nM104 S200 ; set extruder temp\nM109 S200 ; wait for extruder temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\n\nG28 ; Home all axes\nM104 S[first_layer_temperature] ; set extruder temp \nBED_MESH_CALIBRATE AREA_START={first_layer_print_min[0]},{first_layer_print_min[1]} AREA_END={first_layer_print_max[0]},{first_layer_print_max[1]}\n\nG1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed\nM109 S[first_layer_temperature] ; wait for extruder temp\nG1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position\n\nG1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line\nG1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little\nG1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line\nG92 E0 ; Reset Extruder\nG1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed\nG1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.36
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 1
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 30
; top_solid_layers = 4
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 100
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
