; generated by PrusaSlicer 2.6.0-rc2+win64 on 2023-06-19 at 10:55:03 UTC

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

;TYPE:Custom
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

M140 S50 ; set bed temp
M190 S50 ; wait for bed temp

G28 ; Home all axes
M104 S205 ; set extruder temp 
BED_MESH_CALIBRATE AREA_START=87.1802,87.1802 AREA_END=143.82,143.82

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
M109 S205 ; wait for extruder temp
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position

G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.2


G1 E-1.6 F2400
G1 Z.2 F6000
;AFTER_LAYER_CHANGE
;0.2
G1 X88.844 Y87.842
G1 E1.6 F2400
M204 S500
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X90.5 Y87.369 E.04806
G1 X140.5 Y87.369 E1.39527
G1 X142.02 Y87.762 E.04381
G1 X143.158 Y88.844 E.04382
G1 X143.631 Y90.5 E.04806
G1 X143.631 Y140.5 E1.39527
G1 X143.238 Y142.02 E.04381
G1 X142.156 Y143.158 E.04382
G1 X140.5 Y143.631 E.04806
G1 X90.5 Y143.631 E1.39527
G1 X88.98 Y143.238 E.04381
G1 X87.842 Y142.156 E.04382
G1 X87.369 Y140.5 E.04806
G1 X87.369 Y90.5 E1.39527
G1 X87.762 Y88.98 E.04381
G1 X88.803 Y87.886 E.04214
G1 X89.085 Y88.183 F6000
G1 F1200
G1 X89.205 Y88.069 E.00462
G1 X90.5 Y87.746 E.03724
G1 X140.5 Y87.746 E1.39527
G1 X141.917 Y88.139 E.04103
G1 X142.931 Y89.205 E.04106
G1 X143.254 Y90.5 E.03724
G1 X143.254 Y140.5 E1.39527
G1 X142.861 Y141.917 E.04103
G1 X141.795 Y142.931 E.04106
G1 X140.5 Y143.254 E.03724
G1 X90.5 Y143.254 E1.39527
G1 X89.083 Y142.861 E.04103
G1 X88.069 Y141.795 E.04106
G1 X87.746 Y140.5 E.03724
G1 X87.746 Y90.5 E1.39527
G1 X88.139 Y89.083 E.04103
G1 X89.042 Y88.224 E.03478
G1 X89.301 Y88.534 F6000
G1 F1200
G1 X89.56 Y88.317 E.00943
G1 X90.5 Y88.123 E.02678
G1 X140.5 Y88.123 E1.39527
G1 X141.807 Y88.515 E.03808
G1 X142.683 Y89.56 E.03805
G1 X142.877 Y90.5 E.02678
G1 X142.877 Y140.5 E1.39527
G1 X142.485 Y141.807 E.03808
G1 X141.44 Y142.683 E.03805
G1 X140.5 Y142.877 E.02678
G1 X90.5 Y142.877 E1.39527
G1 X89.193 Y142.485 E.03808
G1 X88.317 Y141.44 E.03805
G1 X88.123 Y140.5 E.02678
G1 X88.123 Y90.5 E1.39527
G1 X88.515 Y89.193 E.03808
G1 X89.255 Y88.572 E.02696
; printing object 50x50 single layer.stl id:0 copy 0
G1 E-1.12 F2400
;WIPE_START
G1 F4800
G1 X89.56 Y88.317 E-.18884
G1 X90.16 Y88.193 E-.29116
;WIPE_END
G1 X91.187 Y91.187 F6000
G1 E1.6 F2400
;TYPE:Perimeter
G1 F1200
G1 X139.813 Y91.187 E1.35692
G1 X139.813 Y139.813 E1.35692
G1 X91.187 Y139.813 E1.35692
G1 X91.187 Y91.247 E1.35525
G1 X90.81 Y90.81 F6000
;TYPE:External perimeter
G1 F1200
G1 X140.19 Y90.81 E1.37796
G1 X140.19 Y140.19 E1.37796
G1 X90.81 Y140.19 E1.37796
G1 X90.81 Y90.87 E1.37629
G1 X91.196 Y90.914 F6000
G1 E-1.12 F2400
;WIPE_START
G1 F4800
G1 X91.821 Y90.869 E-.48
;WIPE_END
G1 X139.692 Y92.073 F6000
G1 E1.6 F2400
;TYPE:Solid infill
;WIDTH:0.421259
G1 F1200
G1 X139.097 Y91.477 E.02358
G1 X138.562 Y91.477 E.01498
G1 X139.523 Y92.438 E.03805
G1 X139.523 Y92.973 E.01498
G1 X138.027 Y91.477 E.05924
G1 X137.492 Y91.477 E.01498
G1 X139.523 Y93.508 E.08042
G1 X139.523 Y94.043 E.01498
G1 X136.957 Y91.477 E.1016
G1 X136.422 Y91.477 E.01498
G1 X139.523 Y94.578 E.12279
G1 X139.523 Y95.113 E.01498
G1 X135.887 Y91.477 E.14397
G1 X135.352 Y91.477 E.01498
G1 X139.523 Y95.648 E.16515
G1 X139.523 Y96.183 E.01498
G1 X134.817 Y91.477 E.18634
G1 X134.282 Y91.477 E.01498
G1 X139.523 Y96.718 E.20752
G1 X139.523 Y97.254 E.01501
G1 X133.746 Y91.477 E.22875
G1 X133.211 Y91.477 E.01498
G1 X139.523 Y97.789 E.24993
G1 X139.523 Y98.324 E.01498
G1 X132.676 Y91.477 E.27111
G1 X132.141 Y91.477 E.01498
G1 X139.523 Y98.859 E.2923
G1 X139.523 Y99.394 E.01498
G1 X131.606 Y91.477 E.31348
G1 X131.071 Y91.477 E.01498
G1 X139.523 Y99.929 E.33466
G1 X139.523 Y100.464 E.01498
G1 X130.536 Y91.477 E.35585
G1 X130.001 Y91.477 E.01498
G1 X139.523 Y100.999 E.37703
G1 X139.523 Y101.534 E.01498
G1 X129.466 Y91.477 E.39822
G1 X128.931 Y91.477 E.01498
G1 X139.523 Y102.069 E.4194
G1 X139.523 Y102.604 E.01498
G1 X128.396 Y91.477 E.44058
G1 X127.861 Y91.477 E.01498
G1 X139.523 Y103.139 E.46177
G1 X139.523 Y103.674 E.01498
G1 X127.326 Y91.477 E.48295
G1 X126.791 Y91.477 E.01498
G1 X139.523 Y104.209 E.50413
G1 X139.523 Y104.744 E.01498
G1 X126.256 Y91.477 E.52532
G1 X125.721 Y91.477 E.01498
G1 X139.523 Y105.279 E.5465
G1 X139.523 Y105.814 E.01498
G1 X125.186 Y91.477 E.56769
G1 X124.651 Y91.477 E.01498
G1 X139.523 Y106.349 E.58887
G1 X139.523 Y106.884 E.01498
G1 X124.116 Y91.477 E.61005
G1 X123.58 Y91.477 E.01501
G1 X139.523 Y107.42 E.63128
G1 X139.523 Y107.955 E.01498
G1 X123.045 Y91.477 E.65246
G1 X122.51 Y91.477 E.01498
G1 X139.523 Y108.49 E.67364
G1 X139.523 Y109.025 E.01498
G1 X121.975 Y91.477 E.69483
G1 X121.44 Y91.477 E.01498
G1 X139.523 Y109.56 E.71601
G1 X139.523 Y110.095 E.01498
G1 X120.905 Y91.477 E.7372
G1 X120.37 Y91.477 E.01498
G1 X139.523 Y110.63 E.75838
G1 X139.523 Y111.165 E.01498
G1 X119.835 Y91.477 E.77956
G1 X119.3 Y91.477 E.01498
G1 X139.523 Y111.7 E.80075
G1 X139.523 Y112.235 E.01498
G1 X118.765 Y91.477 E.82193
G1 X118.23 Y91.477 E.01498
G1 X139.523 Y112.77 E.84312
G1 X139.523 Y113.305 E.01498
G1 X117.695 Y91.477 E.8643
G1 X117.16 Y91.477 E.01498
G1 X139.523 Y113.84 E.88548
G1 X139.523 Y114.375 E.01498
G1 X116.625 Y91.477 E.90667
G1 X116.09 Y91.477 E.01498
G1 X139.523 Y114.91 E.92785
G1 X139.523 Y115.445 E.01498
G1 X115.555 Y91.477 E.94903
G1 X115.02 Y91.477 E.01498
G1 X139.523 Y115.98 E.97022
G1 X139.523 Y116.515 E.01498
G1 X114.485 Y91.477 E.9914
G1 X113.95 Y91.477 E.01498
G1 X139.523 Y117.05 E1.01259
G1 X139.523 Y117.586 E.01501
G1 X113.415 Y91.477 E1.03379
G1 X112.879 Y91.477 E.01501
G1 X139.523 Y118.121 E1.05499
G1 X139.523 Y118.656 E.01498
G1 X112.344 Y91.477 E1.07618
G1 X111.809 Y91.477 E.01498
G1 X139.523 Y119.191 E1.09736
G1 X139.523 Y119.726 E.01498
G1 X111.274 Y91.477 E1.11854
G1 X110.739 Y91.477 E.01498
G1 X139.523 Y120.261 E1.13973
G1 X139.523 Y120.796 E.01498
G1 X110.204 Y91.477 E1.16091
G1 X109.669 Y91.477 E.01498
G1 X139.523 Y121.331 E1.1821
G1 X139.523 Y121.866 E.01498
G1 X109.134 Y91.477 E1.20328
G1 X108.599 Y91.477 E.01498
G1 X139.523 Y122.401 E1.22446
G1 X139.523 Y122.936 E.01498
G1 X108.064 Y91.477 E1.24565
G1 X107.529 Y91.477 E.01498
G1 X139.523 Y123.471 E1.26683
G1 X139.523 Y124.006 E.01498
G1 X106.994 Y91.477 E1.28801
G1 X106.459 Y91.477 E.01498
G1 X139.523 Y124.541 E1.3092
G1 X139.523 Y125.076 E.01498
G1 X105.924 Y91.477 E1.33038
G1 X105.389 Y91.477 E.01498
G1 X139.523 Y125.611 E1.35157
G1 X139.523 Y126.146 E.01498
G1 X104.854 Y91.477 E1.37275
G1 X104.319 Y91.477 E.01498
G1 X139.523 Y126.681 E1.39393
G1 X139.523 Y127.216 E.01498
G1 X103.784 Y91.477 E1.41512
G1 X103.249 Y91.477 E.01498
G1 X139.523 Y127.751 E1.4363
G1 X139.523 Y128.287 E.01501
G1 X102.713 Y91.477 E1.45752
G1 X102.178 Y91.477 E.01498
G1 X139.523 Y128.822 E1.47871
G1 X139.523 Y129.357 E.01498
G1 X101.643 Y91.477 E1.49989
G1 X101.108 Y91.477 E.01498
G1 X139.523 Y129.892 E1.52108
G1 X139.523 Y130.427 E.01498
G1 X100.573 Y91.477 E1.54226
G1 X100.038 Y91.477 E.01498
G1 X139.523 Y130.962 E1.56344
G1 X139.523 Y131.497 E.01498
G1 X99.503 Y91.477 E1.58463
G1 X98.968 Y91.477 E.01498
G1 X139.523 Y132.032 E1.60581
G1 X139.523 Y132.567 E.01498
G1 X98.433 Y91.477 E1.627
G1 X97.898 Y91.477 E.01498
G1 X139.523 Y133.102 E1.64818
G1 X139.523 Y133.637 E.01498
G1 X97.363 Y91.477 E1.66936
G1 X96.828 Y91.477 E.01498
G1 X139.523 Y134.172 E1.69055
G1 X139.523 Y134.707 E.01498
G1 X96.293 Y91.477 E1.71173
G1 X95.758 Y91.477 E.01498
G1 X139.523 Y135.242 E1.73291
G1 X139.523 Y135.777 E.01498
G1 X95.223 Y91.477 E1.7541
G1 X94.688 Y91.477 E.01498
G1 X139.523 Y136.312 E1.77528
G1 X139.523 Y136.847 E.01498
G1 X94.153 Y91.477 E1.79647
G1 X93.618 Y91.477 E.01498
G1 X139.523 Y137.382 E1.81765
G1 X139.523 Y137.917 E.01498
G1 X93.083 Y91.477 E1.83883
G1 X92.547 Y91.477 E.01501
G1 X139.523 Y138.453 E1.86006
G1 X139.523 Y138.988 E.01498
G1 X92.012 Y91.477 E1.88124
G1 X91.477 Y91.477 E.01498
G1 X139.523 Y139.523 E1.90242
G1 X138.987 Y139.523 E.01501
G1 X91.477 Y92.013 E1.8812
G1 X91.477 Y92.548 E.01498
G1 X138.452 Y139.523 E1.86002
G1 X137.917 Y139.523 E.01498
G1 X91.477 Y93.083 E1.83883
G1 X91.477 Y93.618 E.01498
G1 X137.382 Y139.523 E1.81765
G1 X136.847 Y139.523 E.01498
G1 X91.477 Y94.153 E1.79647
G1 X91.477 Y94.688 E.01498
G1 X136.312 Y139.523 E1.77528
G1 X135.777 Y139.523 E.01498
G1 X91.477 Y95.223 E1.7541
G1 X91.477 Y95.758 E.01498
G1 X135.242 Y139.523 E1.73291
G1 X134.707 Y139.523 E.01498
G1 X91.477 Y96.293 E1.71173
G1 X91.477 Y96.828 E.01498
G1 X134.172 Y139.523 E1.69055
G1 X133.637 Y139.523 E.01498
G1 X91.477 Y97.363 E1.66936
G1 X91.477 Y97.898 E.01498
G1 X133.102 Y139.523 E1.64818
G1 X132.567 Y139.523 E.01498
G1 X91.477 Y98.433 E1.627
G1 X91.477 Y98.968 E.01498
G1 X132.032 Y139.523 E1.60581
G1 X131.497 Y139.523 E.01498
G1 X91.477 Y99.503 E1.58463
G1 X91.477 Y100.038 E.01498
G1 X130.962 Y139.523 E1.56344
G1 X130.427 Y139.523 E.01498
G1 X91.477 Y100.573 E1.54226
G1 X91.477 Y101.108 E.01498
G1 X129.892 Y139.523 E1.52108
G1 X129.357 Y139.523 E.01498
G1 X91.477 Y101.643 E1.49989
G1 X91.477 Y102.179 E.01501
G1 X128.821 Y139.523 E1.47867
G1 X128.286 Y139.523 E.01498
G1 X91.477 Y102.714 E1.45749
G1 X91.477 Y103.249 E.01498
G1 X127.751 Y139.523 E1.4363
G1 X127.216 Y139.523 E.01498
G1 X91.477 Y103.784 E1.41512
G1 X91.477 Y104.319 E.01498
G1 X126.681 Y139.523 E1.39393
G1 X126.146 Y139.523 E.01498
G1 X91.477 Y104.854 E1.37275
G1 X91.477 Y105.389 E.01498
G1 X125.611 Y139.523 E1.35157
G1 X125.076 Y139.523 E.01498
G1 X91.477 Y105.924 E1.33038
G1 X91.477 Y106.459 E.01498
G1 X124.541 Y139.523 E1.3092
G1 X124.006 Y139.523 E.01498
G1 X91.477 Y106.994 E1.28801
G1 X91.477 Y107.529 E.01498
G1 X123.471 Y139.523 E1.26683
G1 X122.936 Y139.523 E.01498
G1 X91.477 Y108.064 E1.24565
G1 X91.477 Y108.599 E.01498
G1 X122.401 Y139.523 E1.22446
G1 X121.866 Y139.523 E.01498
G1 X91.477 Y109.134 E1.20328
G1 X91.477 Y109.669 E.01498
G1 X121.331 Y139.523 E1.1821
G1 X120.796 Y139.523 E.01498
G1 X91.477 Y110.204 E1.16091
G1 X91.477 Y110.739 E.01498
G1 X120.261 Y139.523 E1.13973
G1 X119.726 Y139.523 E.01498
G1 X91.477 Y111.274 E1.11854
G1 X91.477 Y111.809 E.01498
G1 X119.191 Y139.523 E1.09736
G1 X118.655 Y139.523 E.01501
G1 X91.477 Y112.345 E1.07614
G1 X91.477 Y112.88 E.01498
G1 X118.12 Y139.523 E1.05495
G1 X117.585 Y139.523 E.01498
G1 X91.477 Y113.415 E1.03377
G1 X91.477 Y113.95 E.01498
G1 X117.05 Y139.523 E1.01259
G1 X116.515 Y139.523 E.01498
G1 X91.477 Y114.485 E.9914
G1 X91.477 Y115.02 E.01498
G1 X115.98 Y139.523 E.97022
G1 X115.445 Y139.523 E.01498
G1 X91.477 Y115.555 E.94903
G1 X91.477 Y116.09 E.01498
G1 X114.91 Y139.523 E.92785
G1 X114.375 Y139.523 E.01498
G1 X91.477 Y116.625 E.90667
G1 X91.477 Y117.16 E.01498
G1 X113.84 Y139.523 E.88548
G1 X113.305 Y139.523 E.01498
G1 X91.477 Y117.695 E.8643
G1 X91.477 Y118.23 E.01498
G1 X112.77 Y139.523 E.84312
G1 X112.235 Y139.523 E.01498
G1 X91.477 Y118.765 E.82193
G1 X91.477 Y119.3 E.01498
G1 X111.7 Y139.523 E.80075
G1 X111.165 Y139.523 E.01498
G1 X91.477 Y119.835 E.77956
G1 X91.477 Y120.37 E.01498
G1 X110.63 Y139.523 E.75838
G1 X110.095 Y139.523 E.01498
G1 X91.477 Y120.905 E.7372
G1 X91.477 Y121.44 E.01498
G1 X109.56 Y139.523 E.71601
G1 X109.025 Y139.523 E.01498
G1 X91.477 Y121.975 E.69483
G1 X91.477 Y122.511 E.01501
G1 X108.489 Y139.523 E.67361
G1 X107.954 Y139.523 E.01498
G1 X91.477 Y123.046 E.65242
G1 X91.477 Y123.581 E.01498
G1 X107.419 Y139.523 E.63124
G1 X106.884 Y139.523 E.01498
G1 X91.477 Y124.116 E.61005
G1 X91.477 Y124.651 E.01498
G1 X106.349 Y139.523 E.58887
G1 X105.814 Y139.523 E.01498
G1 X91.477 Y125.186 E.56769
G1 X91.477 Y125.721 E.01498
G1 X105.279 Y139.523 E.5465
G1 X104.744 Y139.523 E.01498
G1 X91.477 Y126.256 E.52532
G1 X91.477 Y126.791 E.01498
G1 X104.209 Y139.523 E.50413
G1 X103.674 Y139.523 E.01498
G1 X91.477 Y127.326 E.48295
G1 X91.477 Y127.861 E.01498
G1 X103.139 Y139.523 E.46177
G1 X102.604 Y139.523 E.01498
G1 X91.477 Y128.396 E.44058
G1 X91.477 Y128.931 E.01498
G1 X102.069 Y139.523 E.4194
G1 X101.534 Y139.523 E.01498
G1 X91.477 Y129.466 E.39822
G1 X91.477 Y130.001 E.01498
G1 X100.999 Y139.523 E.37703
G1 X100.464 Y139.523 E.01498
G1 X91.477 Y130.536 E.35585
G1 X91.477 Y131.071 E.01498
G1 X99.929 Y139.523 E.33466
G1 X99.394 Y139.523 E.01498
G1 X91.477 Y131.606 E.31348
G1 X91.477 Y132.141 E.01498
G1 X98.859 Y139.523 E.2923
G1 X98.323 Y139.523 E.01501
G1 X91.477 Y132.677 E.27107
G1 X91.477 Y133.212 E.01498
G1 X97.788 Y139.523 E.24989
G1 X97.253 Y139.523 E.01498
G1 X91.477 Y133.747 E.22871
G1 X91.477 Y134.282 E.01498
G1 X96.718 Y139.523 E.20752
G1 X96.183 Y139.523 E.01498
G1 X91.477 Y134.817 E.18634
G1 X91.477 Y135.352 E.01498
G1 X95.648 Y139.523 E.16515
G1 X95.113 Y139.523 E.01498
G1 X91.477 Y135.887 E.14397
G1 X91.477 Y136.422 E.01498
G1 X94.578 Y139.523 E.12279
G1 X94.043 Y139.523 E.01498
G1 X91.477 Y136.957 E.1016
G1 X91.477 Y137.492 E.01498
G1 X93.508 Y139.523 E.08042
G1 X92.973 Y139.523 E.01498
G1 X91.477 Y138.027 E.05924
G1 X91.477 Y138.562 E.01498
G1 X92.438 Y139.523 E.03805
G1 X91.903 Y139.523 E.01498
G1 X91.308 Y138.927 E.02358
; stop printing object 50x50 single layer.stl id:0 copy 0
G1 E-1.12 F2400
;WIPE_START
G1 F4800;_WIPE
G1 X91.903 Y139.523 E-.40003
G1 F4800;_WIPE
G1 X92.071 Y139.523 E-.07997
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z2.2 F600 ; Move print head up
G1 X5 Y193.8 F6000 ; present print
G1 Z70.2 F600 ; Move print head further up
G1 Z150 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
; filament used [mm] = 232.62
; filament used [cm3] = 0.56
; filament used [g] = 0.69
; filament cost = 0.01
; total filament used [g] = 0.69
; total filament cost = 0.01
; estimated printing time (normal mode) = 6m 41s
; estimated first layer printing time (normal mode) = 6m 41s

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 3x3,228x3,228x228,3x228
; bed_temperature = 50
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0
; bridge_acceleration = 250
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/(ENDER|CR|SERMOON).*/ and nozzle_diameter[0]==0.4";"printer_notes!~/.*PRINTER_VENDOR_TRILAB.*/ and printer_notes!~/.*PRINTER_MODEL_MK4IS.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and num_extruders>1)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 500
; default_filament_profile = "Generic PLA @CREALITY"
; default_print_profile = "0.16 mm OPTIMAL (0.4 mm nozzle) @CREALITY"
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.85} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 55
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.89
; extrusion_width = 0.44
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 2
; filament_cooling_initial_speed = 3
; filament_cooling_moves = 1
; filament_cost = 21.5
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 14
; filament_loading_speed_start = 19
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 0
; filament_notes = ""
; filament_ramming_parameters = "130 120 2.70968 2.93548 3.32258 3.83871 4.58065 5.54839 6.51613 7.35484 7.93548 8.16129| 0.05 2.66451 0.45 3.05805 0.95 4.05807 1.45 5.97742 1.95 7.69999 2.45 8.1936 2.95 11.342 3.45 11.4065 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Spectrum PLA @Template - po_kalibracji"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 20
; filament_unloading_speed_start = 100
; filament_vendor = Spectrum
; fill_angle = 45
; fill_density = 10%
; fill_pattern = honeycomb
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 50
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 205
; full_fan_speed_layer = 2
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 25
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.44
; infill_first = 0
; infill_overlap = 23%
; infill_speed = 48
; inherits_cummulative = "0.20 mm NORMAL (0.4 mm nozzle) @CREALITY";;"Creality Ender-3 (0.4 mm nozzle)"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 500
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.32
; max_print_height = 250
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.06
; min_print_speed = 10
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{print_time}_{digits(layer_height,1,2)}mm_{temperature[0]}C_{filament_type[0]}_{printer_model}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.44
; perimeter_generator = classic
; perimeter_speed = 36
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20 mm NORMAL (0.4 mm nozzle) @CREALITY - po_kalibracji
; printer_model = ENDER3
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_ENDER3\nPRINTER_HAS_BOWDEN
; printer_settings_id = Creality Ender-3 (0.4 mm nozzle) - po_kalibracji
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 1.6
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0.2
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirts = 3
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.44
; solid_infill_speed = 45
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = ; Ender 3 Custom Start G-code\nG92 E0 ; Reset Extruder\n\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\n\nG28 ; Home all axes\nM104 S[first_layer_temperature] ; set extruder temp \nBED_MESH_CALIBRATE AREA_START={first_layer_print_min[0]},{first_layer_print_min[1]} AREA_END={first_layer_print_max[0]},{first_layer_print_max[1]}\n\nG1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed\nM109 S[first_layer_temperature] ; wait for extruder temp\nG1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position\n\nG1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line\nG1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little\nG1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line\nG92 E0 ; Reset Extruder\nG1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed\nG1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.36
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 1
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 205
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 8
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 30
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_speed = 100
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
